### PR TITLE
[milestone 1] basic UI

### PR DESCRIPTION
**Pull request by kxxt**
This is part of milestone 1. I opened this PR mainly because there are some UI logic I don't know how to deal with.

I implemented a basic functioning UI. It currently only shows data from one fake address book.

On the category tree:
- Click a category to show the corresponding contacts
- Click the checkbox or double click the label to select/un-select the category

Some questions need to be resolved before moving on:

1. Should we allow selections across multiple address books? Or we just let the user select only one address book instead.
2. Currently the add-on builds the whole category tree when the page loads. Any way to optimize this? Perhaps other add-ons/clients could also change the category data so it's not possible to cache it.
3. Should we allow selection on the right contact list?

Other questions:

1. How to get current tab id. I am (ab)using `activeTab` permission to get the tab id. [This `background.js` example](https://github.com/thundernest/sample-extensions/blob/master/composeBody/background.js) gets the tab id without `activeTab` permission but I don't know how to do that in a popup page.

ToDos:

- light/dark theme support(it's dark theme now)
- optimize algorithms
- make the UI more user friendly
- allow user to select address books
Peek 2022-09-30 20-43

### CODE REVIEW

**Comment by jobisoft** [comment]
Wow, you implemented nested categories!

The original add-on did indeed support nested categories but I did not want to confront you with that from the beginning, so I did not explicitly mention this. But you exceeded my expectations and I need to find more funds as this is beyond milestone-1 requirements. Awesome work.

**A few remarks:**

On the category tree:

* Expansion/Collapse only by clicking on the arrow
* Start fully collapsed
* Double-click on a category should trigger BCC addition of that category (and close the popup)

Seeing the UI makes me wonder if we need to find a different approach for the TO, CC, BCC add action. I do not like the checkboxes. You can use `menu.contextOverride` to build your own context menu for the entries and there have a "add to TO", "add to CC", and "add to BCC" option.
[menuoverride.zip](https://github.com/jobisoft/CategoryManager/files/9685890/menuoverride.zip)

 I personally think there is no need to select multiple categories (for now). Maybe we can add that as an option later, but the default should be without.

**Regarding your questions:**

>  Should we allow selections across multiple address books? Or we just let the user select only one address book instead.

The old UI only showed categories of the selected address book, which is sufficient. As stated above, I do not think we have to worry about multiple selections at all at the moment. It is basically a category browser with the option to pick one and do something with it.

>  Currently the add-on builds the whole category tree when the page loads. Any way to optimize this? Perhaps other add-ons/clients could also change the category data so it's not possible to cache it.

Yeah, that is something for milestone-2. You could build the category tree in your background script at startup and register events for [browser.contacts.onUpdated](https://webextension-api.thunderbird.net/en/102/contacts.html#onupdated) (and onCreated, onDeleted) and update your cached tree.

> Should we allow selection on the right contact list?

Not now. Later we could add category management context menu entries to contact entries.

> How to get current tab id. I am (ab)using activeTab permission to get the tab id. 

I just do 

```
let [tab] = await browser.tabs.query({ active: true, currentWindow: true });
```

I do not review this now and let you continue to commit into the PR, right? Or is there a specific code which you want to have feedback about? I saw you are using ES6 modules. Nice!

**Comment by kxxt** [comment]
> Seeing the UI makes me wonder if we need to find a different approach for the TO, CC, BCC add action. I do not like the checkboxes. You can use menu.contextOverride to build your own context menu for the entries and there have a "add to TO", "add to CC", and "add to BCC" option.
> [menuoverride.zip](https://github.com/jobisoft/CategoryManager/files/9685890/menuoverride.zip)

https://github.com/jobisoft/CategoryManager/pull/85/commits/286a76cd0084600f8f105e3c9f5fe27c1a1ff84a

I added a menu to the popup but it doesn't work. I'm not sure what goes wrong. Could you have a look?

**Comment by jobisoft** [comment]
I got it working, so do not spend time on it, I will post the fix soon. Have to go catch the family.

**Comment by jobisoft** [comment]
So you found a bug in Thunderbird: overrideContext does not work in `compose_action` popups. \o/

I will fix that in Thunderbird Core, but that will take a while, so we have to change your roadmap a bit. I added a `browser_action` to your manifest, which adds the button to the main mail window, and you can continue to develop the UI in the `browser_action` instead of the `compose_action`:

image

The primary action for the popup in the main mail window is to call `browser.compose.beginNew()` and start a new composer with the selected category in to, cc or bcc. The `tab.type` (https://webextension-api.thunderbird.net/en/102/tabs.html#tab) tells you, if you are in a messageCompose tab or not, so you can detect which action is to be performed.

Note: There is a second bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1792399) which eats Categories, so when you start working on milestone-2, you will need to switch to a Thunderbird where this is fixed. I therefore suggest to download Thunderbird Daily (See https://www.thunderbird.net/ bottom right, "Daily Channel") for your further developments. When I fix the bug you have discovered, you will get the fix in Daily directly.

Is this ok with you?

**Comment by kxxt** [comment]
>  added a browser_action to your manifest, which adds the button to the main mail window, and you can continue to develop the UI in the browser_action instead of the compose_action

Actually I used browser_action & firefox to develop this add-on initially. There is a bug preventing me to inspect the add-on in Thunderbird 102.

The "Inspect" button on "Debug Add-ons" page won't work in TB102:

```
Uncaught TypeError: window.arguments is undefined
    loadRequestedUrl chrome://messenger/content/extensionPopup.js:47
    onload chrome://messenger/content/extensionPopup.xhtml:1
    inspectDebugTarget resource://devtools/client/aboutdebugging/src/actions/debug-targets.js:98
    thunk Redux
    inspect resource://devtools/client/aboutdebugging/src/components/debugtarget/InspectAction.js:35
    onClick resource://devtools/client/aboutdebugging/src/components/debugtarget/InspectAction.js:47
```

Currently I'm using thunderbird beta(106.0b1) to debug this add-on.

> Is this ok with you?

Yes, of course.

**Comment by kxxt** [comment]
We do not actually need to detect if mouse is over a category.

We can get the exact element in the event listener of `contextmenu`.

https://github.com/jobisoft/CategoryManager/blob/6c9ec244b394554fbed1e05a1b1b51bf392b32c5/src/popup/popup.mjs#L17-L37

**Comment by kxxt** [comment]
Hi @jobisoft ,

I have finished the development of milestone 1. You can review the code and check to see if I forgot anything.

**Comment by jobisoft** [comment]
I fixed a spelling error and moved theme.mjs to unused. Code looks clean and I did not see any obvious things which would be worth changing. 

At one point we will probably add the "All address books" entry to the list of available address books, which I forgot to mention. So if you design new code for milestone-2, it would be good if you could keep that in mind.

Thanks for your great work.

**Comment by stefan-franz** [comment]
Hello, thank you for your work - please let me make a suggestion for the categories: In the version for TB 91 categories are deleting themselves if there is no address in it (e.g. moving an adress to another category). It would be for me better if the category stays and an option would be, to delete the category manually. 
Greetings, Stefan

**Comment by kxxt** [comment]
> Hello, thank you for your work - please let me make a suggestion for the categories: In the version for TB 91 categories are deleting themselves if there is no address in it (e.g. moving an adress to another category). It would be for me better if the category stays and an option would be, to delete the category manually. 
> Greetings, Stefan

Unfortunately, there is currently no way to do so because this addon doesn't store categories. Instead, it scans all contacts and extract categories from them. 

Here is a temporary workaround that might help(for the new version): create a contact without email field but with the categories you want to keep. This way, the category won't be deleted if there are no other contacts in this category and this empty contact will not be included in CC/BCC field if you CC/BCC this category.

**Comment by jobisoft** [comment]
@stefan-franz : Please do not distract @kxxt while he is doing the initial port to Thunderbird 102. When everything is done, you can create new issues with feature request.

**Pull request merged**
