### PR TITLE
fix: add listeners for address book events and other tiny fixes

### PR DESCRIPTION
**Pull request by kxxt**

### CODE REVIEW

**Comment by kxxt** [comment]
Hi @jobisoft ,
I have added listeners for address book events. But there is a bug regarding address book creation.

It seems that the event for contact changes fired before the address book was created in the cache.
I tried to add a breakpoint in `createContactInCache`:

```js
export async function createContactInCache(addressBook, contactNode) {
  if(addressBook == null) debugger;
  ...
}
```

The breakpoint got hit but other event handlers continued execution. It seems weird since JavaScript is single threaded.
By the way, in this case, errors won't be logged to the console of DevTools. The errors are logged to the stdout instead.

```js
JavaScript warning: resource://devtools/server/actors/utils/event-loop.js, line 82: debuggee 'self-hosted:945' would run
JavaScript error: moz-extension://97df83e7-be8d-4df6-ae5b-22dcc856a917/modules/contacts/contact.mjs, line 99: TypeError: (destructured parameter).properties is undefined
JavaScript error: undefined, line 20: Error: An unexpected error occurred
JavaScript error: undefined, line 20: Error: An unexpected error occurred
JavaScript error: undefined, line 20: Error: An unexpected error occurred
JavaScript error: undefined, line 20: Error: An unexpected error occurred
JavaScript error: undefined, line 20: Error: An unexpected error occurred
JavaScript error: undefined, line 20: Error: An unexpected error occurred
JavaScript error: undefined, line 20: Error: An unexpected error occurred
...
```
Do you have any idea about what is going on?

**Comment by jobisoft** [comment]
In order to improve maintainability, I removed categoryPathToString() which is just a special case for getParentCategoryStr() and it was only used once.

I renamed isLeafCategory() to hasSubcategories() (and inverted its logic). The term "leaf" is correctly used as we work with a tree, but I always had to think a couple of seconds when I encountered it while reading the code, what it actually means.

**Comment by jobisoft** [comment]
> Hi @jobisoft ,
> I have added listeners for address book events. But there is a bug regarding address book creation.

How did you get there? Did you add a CardDAV book which then populated its contacts or did you create a local book and manually added a contact?

When I add a CardDAV book I get the book-created event. I get it almost directly, before all its contacts are downloaded, but I do not get any contact-create events for that batch add. After the initial adding is done and then I manually add one, I get the contact-create event.

Do you see the same thing?

I have no real answer to the breakpoint question...

**Comment by kxxt** [comment]
> How did you get there? Did you add a CardDAV book which then populated its contacts or did you create a local book and manually added a contact?

I imported a vcf file in the ThunderBird address book tab. And there are no errors in the devtools console but there are errors in ThunderBird's stdout, which indicates that the contact related events fired before the addressBook was created in the Map. 

Is the contact import tool doing any thing weird?

This is the vcf file:

[vcfzipped.zip](https://github.com/jobisoft/CategoryManager/files/10366047/vcfzipped.zip)

**Comment by jobisoft** [comment]
That import works without errors here (with the PR applied, do not know if that makes a difference), on Daily 110.0a1 (2023-01-06) (64-bit) and also on 102:

image

If you really get the events in the wrong order, then we need to implement events stashing. If we get an update event for an address book, which does not exists (precisely: which we have not yet been notified of), push the event and its data elements into a pending array. When we get the event for creating the address book, we execute that event as usual and then check if there are any pending contact events and execute them as well. Would that work?

**Comment by jobisoft** [comment]
By the way, I mostly use console.log for general debugging. Halting the code on events where we get multiple such events is always somewhat strange. I usually use the debugger only for single events where I know slowing down the execution is not piling stuff up and the execution order is expected to be very linear.

**Comment by kxxt** [comment]
Did you checked the stdout of ThunderBird? In my case, if I remove the break point, the "unexpected errors" disappeared but there are still two errors:

```js
JavaScript error: moz-extension://97df83e7-be8d-4df6-ae5b-22dcc856a917/modules/cache/update.mjs, line 22: TypeError: can't access property "contacts", addressBook is undefined
JavaScript error: moz-extension://97df83e7-be8d-4df6-ae5b-22dcc856a917/modules/contacts/contact.mjs, line 99: TypeError: (destructured parameter).properties is undefined
```

**Comment by kxxt** [comment]
This is what it looks like in debugger when the break point gets hit.

callstack

**Comment by jobisoft** [comment]
Can you re-post that error console after you have pulled the latest changes of this PR, so we both have the same code? Your line numbers do not seem to match mine.

**Comment by jobisoft** [comment]
The code which is calling that function is probably this:

```
async function updateCacheOnContactCreation(addressBooks, node) {
  console.log("updateCacheOnContactCreation");
  let addressBookId = node.parentId;
  await createContactInCache(addressBooks.get(addressBookId), node);
  await createContactInCache(addressBooks.get("all-contacts"), node);
}
```
in listeners.mjs.

So it looks like the call to `addressBooks.get(addressBookId)` really returns nothing, because we have that book not yet cached.

Could you comment out the two calls to `createContactInCache` (or just the first one)? We should then see on the console the order of events.

**Comment by kxxt** [comment]
I have found out what happened. `createContactInCache` was called twice for most of the contacts. Once for the onAddressBookCreated. Once for onContactCreated.

But for the first contact in the newly created address book. There is an incorrect onContactCreated event, potentially a bug in thunderbird itself.

console

**Comment by jobisoft** [comment]
> I have found out what happened. createContactInCache was called twice for most of the contacts.

It is called twice because we add it to the virtual all-contacts book as well, not?

`createContactInCache()` is one level too deep to really see the issued events. Could you follow my suggestion in https://github.com/jobisoft/CategoryManager/pull/90#issuecomment-1374451254 and https://github.com/jobisoft/CategoryManager/pull/90#issuecomment-1374452744 and see what happens?

**Comment by kxxt** [comment]
Here are the errors from stdout after I pulled your changes:

```
JavaScript error: moz-extension://97df83e7-be8d-4df6-ae5b-22dcc856a917/modules/cache/update.mjs, line 28: TypeError: can't access property "contacts", addressBook is undefined
JavaScript error: moz-extension://97df83e7-be8d-4df6-ae5b-22dcc856a917/modules/contacts/contact.mjs, line 99: TypeError: (destructured parameter).properties is undefined
```

**Comment by jobisoft** [comment]
Oh you are right. 

```
async function updateCacheOnAddressBookCreation(addressBooks, node) {
  console.log("updateCacheOnAddressBookCreation");
  // 1. Create the new address book
  const newAddressBook = await AddressBook.fromTBAddressBook(node);
  addressBooks.set(node.id, newAddressBook);
  // 2. Update the "all-contacts" address book
  let allContacts = addressBooks.get("all-contacts");
  await createContactsInCache(allContacts, newAddressBook.contacts);
}
```
`updateCacheOnAddressBookCreation()` should not need to call createContactsInCache() for the all-contacts book. The individual onCreated events should take care of that.

I think we need to rewind this completely to see what is going on. We first need make our listener a no-op and just log what is going on. Hold on.

**Comment by jobisoft** [comment]
Can you re-check? It should now only log on the console the order of events. What do you get when you import the vcf?

**Comment by kxxt** [comment]
I have done some debugging by myself.

Changes:
```js

 browser.contacts.onCreated.addListener(async (node) => {
    console.warn("contacts.onCreated", node.properties);
    await updateCacheOnContactCreation(addressBooks, node);
    await callback(addressBooks);
  });

  browser.addressBooks.onCreated.addListener(async (node) => {
    console.error("addressBooks.onCreated", node);
    await updateCacheOnAddressBookCreation(addressBooks, node);
    await callback(addressBooks);
  });

...

async function updateCacheOnAddressBookCreation(addressBooks, node) {
  console.log("updateCacheOnAddressBookCreation");
  // 1. Create the new address book
  const newAddressBook = await AddressBook.fromTBAddressBook(node);
  addressBooks.set(node.id, newAddressBook);
  console.error("created new address book in cache", newAddressBook);
  // // 2. Update the "all-contacts" address book
  // let allContacts = addressBooks.get("all-contacts");
  // await createContactsInCache(allContacts, newAddressBook.contacts);
}
```

And contacts.onCreated fired after addressBooks.onCreated. But the execution order looks weird.

**Comment by jobisoft** [comment]
For debugging you really need to make the listeners no-op. Any call which you are awaiting is changing the execution order (the function steps out when hitting an await and executes the next code waiting in line). That is why I removed all (async) code in my debug setup commit.

**Comment by kxxt** [comment]
Here is the output after I pulled your changes:



>  Any call which you are awaiting is changing the execution order (the function steps out when hitting an await and executes the next code waiting in line). 

So do we need to find a way to make the listener for onAddressBookCreation synchronous?

**Comment by jobisoft** [comment]
I think we have to defer contact events if the corresponding address book has not yet been cached. What happens is that the async process to cache the AB is postponed and then the new contact events come to early.

So in the 3 contact listeners we have to check, if we know the corresponding AB (if it exists in the cache). If not we can do 2 things:
a) use a local defer, a set timeout which calls the listener with the same arguments again in 250ms
b) add the event to a global contacts event log, which we clear once we have cached the AB

The local defer is faster and easier to implement to see if it fixes your issue. I think it is sufficient for now. We can just add a comment about the other cleaner option.

I will back out the debug commits now.

**Comment by kxxt** [comment]
So the reason for that error is that the operation for onAddressBookCreation is not atomic and we need a lock here. It can be implemented cleanly using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics and we don't need setTimeout

**Comment by jobisoft** [comment]
And the address book cache in `updateCacheOnAddressBookCreation()` must not add any contacts, so I think all we have to do is to add an empty address book to the cache.

**Comment by jobisoft** [comment]
> So the reason for that error is that the operation for onAddressBookCreation is not atomic and we need a lock here. It can be implemented cleanly using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics and we don't need setTimeout

Hm, I do not think that will help. But if you want you can give it a try.

However - coming back to your comment in https://github.com/jobisoft/CategoryManager/pull/90#issuecomment-1374463589 - if the address book cache action is just to add an empty book to the cache, this could be a sync operation and then we do not need any of that and simply make that listener sync.

**Comment by kxxt** [comment]
Oops, this is unfortunate:



Perhaps we still need `setTimeout` if `Atomics.wait` blocks the thread.

**Comment by jobisoft** [comment]
> Oops, this is unfortunate:

What a pitty. 

> Perhaps we still need setTimeout

Coming back to your comment in https://github.com/jobisoft/CategoryManager/pull/90#issuecomment-1374463589 - if the address book cache action is just to add an empty book to the cache (contacts will be filled by the follow up events), this could be a sync operation and then we do not need any of that and simply make that listener sync. Could you try that?

**Comment by kxxt** [comment]
> Coming back to your comment in https://github.com/jobisoft/CategoryManager/pull/90#issuecomment-1374463589 - if the address book cache action is just to add an empty book to the cache (contacts will be filled by the follow up events), this could be a sync operation and then we do not need any of that and simply make that listener sync. Could you try that?

I will try this first. It looks nice and I love it.

**Comment by kxxt** [comment]
It works and now this bug is finally fixed!

**Comment by jobisoft** [comment]
Removing an address book does not seem to remove its contacts from the virtual all-contacts book. Does this happen only for me, or do you see that as well?

**Comment by jobisoft** [comment]
Never mind! My cache was invalid.

**Comment by kxxt** [comment]
Ha, it seems github copilot understand why that listener must be sync because it generates a correct comment for that listener after I typed `// This listener`.

**Comment by jobisoft** [comment]
The deferred UI update works PERFECTLY NICE with your updating indicator. I renamed category walkups of you vcf.

**Comment by kxxt** [comment]
I will check to see if there are some ways to make selecting multiple contacts possible. Perhaps I should look at how vscode implements its file system tree view. That would be another PR.

There is an experimental html element called `<selectmenu>` which looks promising but it isn't implemented in any browser. Using a `<select>` here is inappropriate because we basically can't style it.
 
And we can release another preview version after a bug that I mentioned in the email(Not sure if you have read that) get fixed. 

---

> The contacts object is now a Map() and stores the entire contact also for categories, instead of just "null". This allows to sort this map directly. Your own code on contact sort did not make it back in.

There are some issues about this approach (At first, I stored the entire contact like you. I wish I could have explained it to you earlier):

-   (Major issue) When the email and name of a contact has been edited, the cache is partially updated. So when a user BCC a category, a contact with its old email gets BCCed.
  **This is a regression in the current prerelease and we should warn users about it.**
-  (Minor issue) The names and emails get stored too many times, causing a larger memory footprint.
-  (Minor issue) If we want to update the emails and names, we need to do it recursively because the contacts stored in the AddressBook is no longer Single Point of Truth.

**Comment by jobisoft** [comment]
I wanted to reply to your email but was caught up in different things. I will respond to that shortly.

**Comment by kxxt** [comment]
> I wanted to reply to your email but was caught up in different things. I will respond to that shortly.

No need to hurry. I leave that fix up to you. And I have some other things to deal with before sleep.

**Pull request merged**
